### ISSUE TITLE
Support clangd

### ISSUE THREAD

**Issue by Chandlercjy** [ballerina-platform/lsp4intellij#109] opened 2019-07-09 03:27 UTC
**Description:**
clangd will fail to update file due to Change's rangeLength (1) doesn't match the computed range length (0)..

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
all

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**

```java
public class MyLSPComponent implements ProjectComponent {
    private static final Logger LOG = Logger.getLogger("kkk");

    @Override
    public void initComponent() {
        LOG.info("Initializing plugin data structures");
        RawCommandServerDefinition cpp = new RawCommandServerDefinition("cpp", new String[]{"D:\\Program Files\\LLVM\\bin\\clangd.exe","-log=verbose"});
        IntellijLanguageClient.addServerDefinition(cpp);

    }

    @Override
    public void disposeComponent() {
        LOG.info("Disposing plugin data structures");
    }

    @Override
    @NotNull
    public String getComponentName() {
        return "myApplicationComponent";
    }

}
```

1. like matthewmichihara/sample-ballerina-plugin, run  `clangd.exe` with `-log=verbose argument`.
2. open an cpp file, edit it, then the log will show as following:
```
I[11:17:20.372] <-- textDocument/didChange
E[11:17:20.372] Failed to update C:\Users\Chandler\Desktop\cpp\gg.cpp: Change's rangeLength (1) doesn't match the computed range length (0).
```
3. Then clangd will not work.

**My Solution**
delete 1160 line of lsp4intellij\src\main\java\org\wso2\lsp4intellij\editor\EditorEventManager.java
```
              changeEvent.setRangeLength(newTextLength);
```
Then it will work. But I don't know whether it will have some influence on some function?

Could you help me to fix it?
Thank you!

**Comment by NipunaRanasinghe** [comment] 2019-07-10 09:13
@Chandlercjy Seems like your lang server is using incremental synchronization which is less reliable w.r.t. full synchronization. 

If we remove the line 1160, `rangeLength` will be null, which might cause potential LSP violation and unexpected results from the servers which do not have a null guarding for it. could you please debug and see which is the correct range (Change's rangeLength or computed range length) first? If the `rangeLength` is wrong we can proceed with fixing the client side logic. :) WDYT?

**Comment by Trias** [comment] 2020-12-22 10:12
this may be a duplicate of https://github.com/ballerina-platform/lsp4intellij/issues/216 so maybe it's fixed now

**Comment by Chandlercjy** [comment] 2020-12-27 06:31
Fixed

**Closed** 2020-12-27 06:31 UTC
Labels: Severity/Major, Type/Bug
