### ISSUE TITLE
Complementation of the editor which is splited in another group is affected

### ISSUE THREAD

**Issue by SUBYEAR** [ballerina-platform/lsp4intellij#215] opened 2020-08-27 08:38 UTC
**Description:**

I used lsp4intellij develop a laguage supporting feture in intellij. And I found that if i use the 'split' function, the completion of lsp4intellij will be affected. The described 'split' function in intellij is as follwing
![image](https://user-images.githubusercontent.com/25758750/91418947-66ba4800-e885-11ea-85b7-ba1a23433873.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
All
**OS, DB, other environment details and versions:**    
Windows operation sysytem, and latest version
**Steps to reproduce:**
1. open a file in intellij
2. place the cursor on the editor label.
3. click right button of mose, choose 'Split Vertically'
![split](https://user-images.githubusercontent.com/25758750/91419373-ea743480-e885-11ea-9f45-1aaf852723c2.gif)

After that it will appear two same editor, but only one could use the commpletion

**Related Issues:**

**Comment by swissiety** [comment] 2020-10-04 15:05
duplicate of #142

**Comment by NipunaRanasinghe** [comment] 2020-10-15 09:18
@SUBYEAR Closing since a duplicate of #142

**Closed** 2020-10-15 09:19 UTC
Labels: Resolution/Duplicate
