### ISSUE TITLE
Migrating from intellij-lsp to lsp4intellij

### ISSUE THREAD

**Issue by nixel2007** [ballerina-platform/lsp4intellij#4] opened 2019-02-13 05:29 UTC
Hello!

I would like to migrate from scala intellij-lsp to your fork (and give some feedback, as you requested it in README :) ).

Do you support all basic capabilities of old intellij-lsp? At least i need a diagnostics, completion, hover and formatting capabilities.

Do i need to include something more than gradle/mvn dependency from jitpack (e.g.)?
https://jitpack.io/#NipunaRanasinghe/lsp4intellij

As i can see there is similar to intellij-lsp registration process - via preloading task and server definition. No more surprises?

P.S. Big THANK YOU for your work. fork at intellij-community didn't shoot (and i haven't enough free time for this). but i reeaaaly would like to switch to your fork.

**Comment by NipunaRanasinghe** [comment] 2019-02-13 12:09
Hi @nixel2007! First of all, thank you for your interest. It would be a great help if you could test this with your language server and provide some feedback as I requested.

I'm planning to implement all the existing features of the scala plugin. As I mentioned in the README, I've implemented code completion support so far and still working on the other features(currently working on diagnostics in the develop branch). 

> As i can see there is similar to intellij-lsp registration process - via preloading task and server definition. No more surprises? 

Yes of course! The current implementation is almost same as the Scala plugin ( A big thank goes to [@gtache](https://github.com/gtache) for his awesome work! ). I've used raw command server definition in the lsp4intellij-plugin example, but other options should work as well.

> Do i need to include something more than gradle/mvn dependency from jitpack (e.g.)?
https://jitpack.io/#NipunaRanasinghe/lsp4intellij

I tried but unfortunately jitpack didn't work for me :( I'll let you know once that issue is sorted. I'm currently using the local jar file.

**Comment by nixel2007** [comment] 2019-02-13 13:31
Looks like you've faced with the same issue - https://github.com/jitpack/jitpack.io/issues/3737

**Comment by nixel2007** [comment] 2019-02-13 13:32
Ok, thank you! i'll try to migrate in a few days.

If you randomly choose features to implement - please, implement range and document formatting next :D

**Comment by NipunaRanasinghe** [comment] 2019-02-14 06:51
Sure I can work on formatting support after completing diagnostics :D

**Comment by nixel2007** [comment] 2019-02-15 08:27
No luck this time.

```
WARN: Lsp4IntelliJ not loaded: until build 173.SNAPSHOT < IC-183.4284.85
```

I'm using IDEA IC 2018.3.4. Plugin is targeted to `>= 183.4284.85`

Commit with migrating - https://github.com/1c-syntax/intellij-language-1c-bsl/commit/6b65197020bb50448e786b5ce19830aa6f2853d4

**Comment by NipunaRanasinghe** [comment] 2019-02-20 11:37
@nixel2007 Could you please try after changing the build number range in your `plugin.xml`? :) This might help https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html

And please note that I've tested the library only for 173+ . Will add the compatibility information soon.

**Comment by nixel2007** [comment] 2019-02-21 06:04
I've seen your fixes about plugin.xml and untilBuild in gradle. I'll check it asap

**Comment by NipunaRanasinghe** [comment] 2019-02-21 06:18
I've also updated the README. Hope it'll help :)

**Comment by nixel2007** [comment] 2019-02-25 12:05
Could you provide some info about LSPExtensionManager? https://github.com/NipunaRanasinghe/lsp4intellij/blob/de60747f47e0240f7298f1266614f89d6c41230a/src/main/java/com/github/lsp4intellij/extensions/LSPExtensionManager.java

what is designed for? i don't implement it (cause it was not needed in intellij-lsp) and (to be honest) not sure should i implement it and how.

**Comment by NipunaRanasinghe** [comment] 2019-02-25 12:56
@nixel2007 **You don't have to implement it at all**, If don't have any language server protocol extensions (custom capabilities in addition to the Language server Specification) in your language server :) 

That capability is designed to support custom request/response and notifications, which are not in the language server protocol specification. Anyway I'll add a detailed description later, since it is still an experimental component.

Until then all you need to do is,
- Add lsp4intellij as dependency via jitpack
- Update your plugin.xml by registering the capabilities (Refer https://github.com/NipunaRanasinghe/lsp4intellij-plugin/blob/master/src/main/resources/META-INF/plugin.xml)
- Add a preloading activity to register your language server definition.

and thats all! :)

**Comment by nixel2007** [comment] 2019-02-25 12:58
I did all this steps but don't see any diagnostics from my language server. I'll setup a lsp launcher tracer to get some logs and figure out if my lang server even starts.

**Comment by NipunaRanasinghe** [comment] 2019-02-25 13:03
@nixel2007 That would be great if you can verify that. I guess you are also using the `RawCommandServer Definition` option?

**Comment by nixel2007** [comment] 2019-02-25 13:10
@NipunaRanasinghe nope. ExeLanguageServerDefinition - https://github.com/1c-syntax/intellij-language-1c-bsl/blob/feature/lsp4intellij/src/main/java/org/github/_1c_syntax/intellij/bsl/BSLPreloadingActivity.java#L89

**Comment by NipunaRanasinghe** [comment] 2019-02-25 13:18
@nixel2007 could you please try for only one file extension instead of two, since I've still not implemented support for multiple file extensions? :/ 

i.e. String extensions = BSLFileType.INSTANCE.getDefaultExtension();

**Comment by NipunaRanasinghe** [comment] 2019-02-25 13:45
One more thing, did you add the `IntelliJLanguageClient` as the application component as follows?

https://github.com/NipunaRanasinghe/lsp4intellij-plugin/blob/95ecedb19364408acf74c62ac26d59efa2466789/src/main/resources/META-INF/plugin.xml#L30

**Comment by nixel2007** [comment] 2019-02-25 14:23
> One more thing, you must add the `IntelliJLanguageClient` as a application component as follows, since it is the main class.

oh. i missed it. ok, i'll try it.

> could you please try for only one file extension instead of two, since I've still not implemented support for multiple file extensions? :/

sure. may i create an issue for it to be notified, when it'll be done?

**Comment by NipunaRanasinghe** [comment] 2019-02-25 14:46
> sure. may i create an issue for it to be notified, when it'll be done?

Sure, please do :) Probably I can fix that within next 2, 3 days I guess

**Comment by nixel2007** [comment] 2019-02-25 17:38
Okay, adding missed component to plugin.xml and one extension did the trick. but... I have exeptions in idea.log (and server shutdown).

idea.log:
```
2019-02-25 20:29:39,515 [   9691]   INFO - ntellij.IntellijLanguageClient - Added definition for command : path java args : -jar D:\git\1c-syntax\bsl-language-server\build\libs\bsl-language-server-0.4.0-dev+25.dev.jar --diagnosticLanguage ru 
2019-02-25 20:29:39,516 [   9692]   INFO - .openapi.application.Preloader - org.github._1c_syntax.intellij.bsl.BSLPreloadingActivity took 7 ms 
2019-02-25 20:29:39,525 [   9701]   INFO - penapi.project.DumbServiceImpl - Running dumb mode task: com.intellij.util.indexing.UnindexedFilesUpdater@66a1e4a6 
2019-02-25 20:29:39,535 [   9711]   INFO - ntellij.internal.IconsLoadTime - IMG load time: ide_startup=10,43ms, average=0,58ms, median=0,83ms; number of icons: 18 
2019-02-25 20:29:39,535 [   9711]   INFO - ntellij.internal.IconsLoadTime - SVG load time: ide_startup=151,86ms, average=4,22ms, median=6,04ms; number of icons: 36 
2019-02-25 20:29:39,601 [   9777]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 74ms; general responsiveness: ok; EDT responsiveness: ok 
2019-02-25 20:29:40,010 [  10186]   INFO - ntellij.IntellijLanguageClient - Added serverDefinitions [command : path java args : -jar D:\git\1c-syntax\bsl-language-server\build\libs\bsl-language-server-0.4.0-dev+25.dev.jar --diagnosticLanguage ru] from plugins 
2019-02-25 20:29:40,013 [  10189]   INFO - ntellij.IntellijLanguageClient - Opened РаботаСКоннекторами.os 
2019-02-25 20:29:40,014 [  10190]   INFO - ntellij.IntellijLanguageClient - Instantiating wrapper for os : file:///D:D: 
2019-02-25 20:29:40,021 [  10197]   INFO - ntellij.IntellijLanguageClient - Adding file РаботаСКоннекторами.os 
2019-02-25 20:29:40,022 [  10198]  ERROR - plication.impl.ApplicationImpl - String index out of range: -1 
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.github.lsp4intellij.utils.FileUtils.sanitizeURI(FileUtils.java:135)
	at com.github.lsp4intellij.utils.FileUtils.editorToURIString(FileUtils.java:94)
	at com.github.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:257)
	at com.github.lsp4intellij.IntellijLanguageClient.lambda$editorOpened$0(IntellijLanguageClient.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-02-25 20:29:40,026 [  10202]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2018.3  Build #IC-183.4284.85 
2019-02-25 20:29:40,026 [  10202]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-02-25 20:29:40,026 [  10202]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2019-02-25 20:29:40,031 [  10207]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: Language 1C (BSL) version: 0.2.0 
2019-02-25 20:29:40,031 [  10207]  ERROR - plication.impl.ApplicationImpl - Last Action:  
```

after this opening new file throws more errors like this:

```
2019-02-25 20:30:10,238 [  40414]   INFO - ntellij.IntellijLanguageClient - Opened fake-entrypoint.os 
2019-02-25 20:30:10,240 [  40416]   INFO - ntellij.IntellijLanguageClient - Wrapper already existing for os , file:///D:D: 
2019-02-25 20:30:10,240 [  40416]   INFO - ntellij.IntellijLanguageClient - Adding file fake-entrypoint.os 
2019-02-25 20:30:10,241 [  40417]  ERROR - plication.impl.ApplicationImpl - String index out of range: -1 
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.github.lsp4intellij.utils.FileUtils.sanitizeURI(FileUtils.java:135)
	at com.github.lsp4intellij.utils.FileUtils.editorToURIString(FileUtils.java:94)
	at com.github.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:257)
	at com.github.lsp4intellij.IntellijLanguageClient.lambda$editorOpened$0(IntellijLanguageClient.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-02-25 20:30:10,241 [  40417]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2018.3  Build #IC-183.4284.85 
2019-02-25 20:30:10,241 [  40417]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-02-25 20:30:10,241 [  40417]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2019-02-25 20:30:10,242 [  40418]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: Language 1C (BSL) version: 0.2.0 
2019-02-25 20:30:10,242 [  40418]  ERROR - plication.impl.ApplicationImpl - Last Action:  
2019-02-25 20:30:10,242 [  40418]  ERROR - plication.impl.ApplicationImpl - Current Command:  
```

after some moment language server revieves `shutdown` and `exit` events. lsp-trace.log (sorry for long read):

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "initialize",
  "params": {
    "processId": 28364,
    "rootPath": "d:\\git\\nixel2007\\entity",
    "rootUri": "file:///d%3A/git/nixel2007/entity",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "workspaceEdit": {
          "documentChanges": true,
          "resourceOperations": [
            "create",
            "rename",
            "delete"
          ],
          "failureHandling": "textOnlyTransactional"
        },
        "didChangeConfiguration": {
          "dynamicRegistration": true
        },
        "didChangeWatchedFiles": {
          "dynamicRegistration": true
        },
        "symbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26
            ]
          },
          "dynamicRegistration": true
        },
        "executeCommand": {
          "dynamicRegistration": true
        },
        "workspaceFolders": true,
        "configuration": true
      },
      "textDocument": {
        "synchronization": {
          "willSave": true,
          "willSaveWaitUntil": true,
          "didSave": true,
          "dynamicRegistration": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true,
            "commitCharactersSupport": true,
            "documentationFormat": [
              "markdown",
              "plaintext"
            ],
            "deprecatedSupport": true,
            "preselectSupport": true
          },
          "completionItemKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25
            ]
          },
          "contextSupport": true,
          "dynamicRegistration": true
        },
        "hover": {
          "contentFormat": [
            "markdown",
            "plaintext"
          ],
          "dynamicRegistration": true
        },
        "signatureHelp": {
          "signatureInformation": {
            "documentationFormat": [
              "markdown",
              "plaintext"
            ]
          },
          "dynamicRegistration": true
        },
        "references": {
          "dynamicRegistration": true
        },
        "documentHighlight": {
          "dynamicRegistration": true
        },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26
            ]
          },
          "hierarchicalDocumentSymbolSupport": true,
          "dynamicRegistration": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "rangeFormatting": {
          "dynamicRegistration": true
        },
        "onTypeFormatting": {
          "dynamicRegistration": true
        },
        "definition": {
          "dynamicRegistration": true
        },
        "typeDefinition": {
          "dynamicRegistration": true
        },
        "implementation": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "",
                "quickfix",
                "refactor",
                "refactor.extract",
                "refactor.inline",
                "refactor.rewrite",
                "source",
                "source.organizeImports"
              ]
            }
          },
          "dynamicRegistration": true
        },
        "codeLens": {
          "dynamicRegistration": true
        },
        "documentLink": {
          "dynamicRegistration": true
        },
        "colorProvider": {
          "dynamicRegistration": true
        },
        "rename": {
          "prepareSupport": true,
          "dynamicRegistration": true
        },
        "publishDiagnostics": {
          "relatedInformation": true
        },
        "foldingRange": {
          "rangeLimit": 5000,
          "lineFoldingOnly": true,
          "dynamicRegistration": true
        }
      }
    },
    "trace": "off",
    "workspaceFolders": [
      {
        "uri": "file:///d%3A/git/nixel2007/entity",
        "name": "entity"
      }
    ]
  }
}
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "capabilities": {
      "textDocumentSync": 1,
      "documentFormattingProvider": true,
      "documentRangeFormattingProvider": true
    }
  }
}
{
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}
{
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///d%3A/git/nixel2007/entity/tasks/coverage.os",
      "languageId": "bsl",
      "version": 1,
      "text": "some file content"
    }
  }
}
{
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///d%3A/git/nixel2007/entity/tasks/coverage.os",
    "diagnostics": []
  }
}
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "shutdown",
  "params": null
}
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": true
}
{
  "jsonrpc": "2.0",
  "method": "exit",
  "params": null
}

```

**Comment by NipunaRanasinghe** [comment] 2019-02-25 17:55
@nixel2007 Glad it worked :D Seems there is an issue in a uri sensitization util method, and thats why the connection gets crashed.
Could you please let me know,
- your OS details and 
- absolute file path of the file that you were trying to open 
to reproduce the issue?

**Comment by nixel2007** [comment] 2019-02-25 18:17
* Microsoft Windows [Version 10.0.18343.1] (PRO x64, RU locale)
* `d:/git/nixel2007/entity/tasks/coverage.os` (from https://github.com/nixel2007/entity/blob/develop/tasks/coverage.os)

**Comment by NipunaRanasinghe** [comment] 2019-02-26 04:18
Oh that must be a windows specific issue, since I haven't had a time to test it on windows so far. Will fix it ASAP. Again, really your contribution and effort towards this :)

**Comment by NipunaRanasinghe** [comment] 2019-03-13 03:56
@nixel2007 I'm having thoughts of transferring the ownership of this repository to IntelliJ LSP Community. For that
- I may need to slightly change the org name ( from `intellij-lsp` to `intellijcom`? ) since I'll have to request a new maven group id with the org name
- Copyrights of this repository will remain same until I get the approval from my organization

Are you okay with the above concerns? :) Can we proceed??

**Comment by nixel2007** [comment] 2019-03-13 06:41
Good thoughts :)
- I think we could have trademark problem with intellijcom. It is so close to intellij.com and so on. If the maven group id is the main problem, you could request 'org github.intellij-lsp' or something similar? Also we could rename org to lsp4intellij.
- for me copyright ownership is not a problem at all. But GPL have some strong states about considering transpiling to another language as "rework", that should be licensed with the same copyrights ownership (not "author" of concrete files). Is Apache license gives you a permission to put wso2 ownership marks? Or may be there is so much code rewriting and reimplementing that it can not be considering as "rework" in terms of gpl?

**Comment by NipunaRanasinghe** [comment] 2019-03-13 09:01
Thanks for your feedback!
- We can surely use `com. github.intellij-lsp` as a valid group id but since scala plugin is already using that as its name, using another name might be better I guess. Therefore I'm +1 for `lsp4intellij` or any other suggestion you got ;) 
- You seem to be having a valid point :) I'll update you with the final conclusion after having some further discussions

**Comment by nixel2007** [comment] 2019-03-13 09:04
Org was renamed - https://github.com/lsp4intellij
Feel free to transfer ownership when you are ready.

**Comment by NipunaRanasinghe** [comment] 2019-03-13 09:10
Sure will do after sorting out the copyright issue. Thanks for your help towards the process.

**Comment by nixel2007** [comment] 2019-03-13 09:16
> offtopic.
it is so inspiring for me as Russian programmer to work with Sri Lanka's (Sri Lankan? Sri Lankian? 😄) programmer on opensource project, that can be usefull all over the world.

**Comment by NipunaRanasinghe** [comment] 2019-03-13 09:49
> It should be "Sri Lankan" ;) :D We also are so glad to have such a valuable and contributor like you! Let's work together and see how this `lsp4intellij` thing rolls out!

**Comment by NipunaRanasinghe** [comment] 2019-03-26 06:01
@nixel2007 Sorry for the late response since We were having several internal discussions regarding the copyrights and the maven publish thing. In brief, we considered the following factors

-  We have done internal design and architectural reviews and changed the design accordingly (might have to do more in the future). Therefore it is decided that it's reasonable to proceed with the wso2 copyrights.

- Since we'll be using the company copyrights, its better to maintain it as a wso2-driven opensource project (There are many open source projects that are currently being developed and maintained by wso2). Then it'll also be easier for the maven publishing process as well.

WDYT?? :)

**Comment by nixel2007** [comment] 2019-03-26 06:08
Sounds reasonable :) I don't see any cons to this.
So repo will be transfered to wso2 org?

**Comment by NipunaRanasinghe** [comment] 2019-03-26 06:16
Yeah I hope so. I think by this way we'll get more community attraction since the wso2 org (https://github.com/wso2) already has a fairly large number of contributors with 300+ opensource projects. :)

**Comment by gayanper** [comment] 2019-03-26 13:41
@NipunaRanasinghe so if i understand correctly this work will go into wso2 github org instead of lsp4intellij org repo right ? 

I also have some changed i done on original work of this. I think we can add them here as well. I will come up with PRs and improvements for them. I would also like to see this going fwd since intellij have no lsp support plans.

**Comment by nixel2007** [comment] 2019-03-28 11:03
@NipunaRanasinghe I'm a bit surprised by the new repo owner, but it's ok :)

**Comment by gayanper** [comment] 2019-03-28 12:22
Me too 😮

**Comment by NipunaRanasinghe** [comment] 2019-03-28 13:07
Hey guys, Sorry for the surprise! We thought of add this repo under the ballerina org since this was initiated  as a requirement of the ballerina IntelliJ plugin. On the other hand, ballerina organization is 100% opensource :) So think this might be fine for you guys, forgive me again if you guys experienced any issues due to the migration.

**Comment by NipunaRanasinghe** [comment] 2019-03-28 13:09
One more thing, I did a new release today, which is stable in jitpack :) So feel free to try out and contribute!

**Comment by nixel2007** [comment] 2019-03-28 13:21
@NipunaRanasinghe It looks like all core features i need for bsl plugin is implemented here, so after updating deps I'll merge lspintellij-migration branch to master, and we can close this issue :)

**Comment by nixel2007** [comment] 2019-03-28 15:01
@NipunaRanasinghe ah, i am still waiting for info/hints diagnostics.

**Comment by gayanper** [comment] 2019-03-28 16:50
@NipunaRanasinghe Do we really need to fill all the stuff in the PR template ? Seems like bit de-motivational for contributions if we really need to go through the whole process of submitting different documentation to wso2 :)

**Comment by NipunaRanasinghe** [comment] 2019-03-29 04:48
@nixel2007 Forgive me since I'm bit stuck with another work :/ Will try to fix that by the next week for sure :)

@gayanper No you don't :) Its totally okay to fill the purpose and remove the other sections if you got nothing to fill there. Its just the standard template for the wso2 open source projects.

**Comment by NipunaRanasinghe** [comment] 2019-03-29 11:26
@nixel2007 Could you please try with `'com.github.ballerina-platform:lsp4intellij:improved-inspections-SNAPSHOT'` jitpack build? Let me know whether diagnostics are fixed

**Comment by nixel2007** [comment] 2019-03-30 13:15
@NipunaRanasinghe something goes wrong ;(

```
2019-03-30 16:13:19,116 [  10057]   WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 11
  character = 123
] line : 	КлючХранилища = ПолучитьКлючХранилища(ОбъектМодели.ТипСущности(), ТипЗнч(Коннектор), СвойстваКоннектора.СтрокаСоединения); column : 126 offset : 340 
2019-03-30 16:13:19,253 [  10194]  ERROR - emon.impl.LocalInspectionsPass - Tool #LSP registers INFORMATION level problem in batch mode on BSL File. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations 
java.lang.Throwable: Tool #LSP registers INFORMATION level problem in batch mode on BSL File. INFORMATION level 'warnings' are invisible in the editor and should not become visible in batch mode. Moreover, cause INFORMATION level fixes act more like intention actions, they could e.g. change semantics and thus should not be suggested for batch transformations
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInBatch(LocalInspectionsPass.java:141)
	at org.wso2.lsp4intellij.editor.EditorEventManager.lambda$null$8(EditorEventManager.java:520)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at org.wso2.lsp4intellij.editor.EditorEventManager.lambda$runInspection$9(EditorEventManager.java:518)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:435)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-03-30 16:13:19,256 [  10197]  ERROR - emon.impl.LocalInspectionsPass - IntelliJ IDEA 2018.3  Build #IC-183.4284.148 
2019-03-30 16:13:19,257 [  10198]  ERROR - emon.impl.LocalInspectionsPass - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-03-30 16:13:19,257 [  10198]  ERROR - emon.impl.LocalInspectionsPass - OS: Windows 10 
2019-03-30 16:13:19,261 [  10202]  ERROR - emon.impl.LocalInspectionsPass - Plugin to blame: Language 1C (BSL) version: 0.2.0 
2019-03-30 16:13:19,261 [  10202]  ERROR - emon.impl.LocalInspectionsPass - Last Action:  
2019-03-30 16:13:19,382 [  10323]   WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 73
  character = 37
] line : 	ИначеЕсли Отбор = Неопределено Тогда column : 40 offset : 2750 
2019-03-30 16:13:19,383 [  10324]   WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 62
  character = 123
] line : 			ПередаваемыйОтбор.Добавить(Новый ЭлементОтбора(Колонка.ИмяКолонки, ЭлементОтбора.ВидСравнения, ЭлементОтбора.Значение)); column : 132 offset : 2278 
2019-03-30 16:13:19,383 [  10324]   WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 72
  character = 122
] line : 		ПередаваемыйОтбор.Добавить(Новый ЭлементОтбора(Колонка.ИмяКолонки, ЭлементОтбора.ВидСравнения, ЭлементОтбора.Значение)); column : 128 offset : 2712 
2019-03-30 16:13:19,804 [  10745]   WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 264
  character = 135
] line : 		СтрокаУсловий = СтрокаУсловий + СтрШаблон("%1 %2 @%3", ЭлементОтбора.ПутьКДанным, ЭлементОтбора.ВидСравнения, ПредставлениеСчетчика); column : 141 offset : 8546 
```

**Comment by nixel2007** [comment] 2019-03-30 13:28
Part of lsp-trace.log after getting diagnostics:

```
{
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///D:/git/nixel2007/entity/src/Классы/КоннекторSQLite.os",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 264,
            "character": 0
          },
          "end": {
            "line": 264,
            "character": 135
          }
        },
        "severity": 3,
        "code": "LineLength",
        "source": "bsl-language-server",
        "message": "String length exceeded"
      }
    ]
  }
}
{
  "jsonrpc": "2.0",
  "id": "2",
  "method": "shutdown",
  "params": null
}
{
  "jsonrpc": "2.0",
  "id": "2",
  "result": true
}
```

**Comment by gayanper** [comment] 2019-04-08 14:01
@NipunaRanasinghe registering the LSP contributors and app component on each plugin which uses this library going to be a problem right ? I mean even if i have two instance registration of autocomplete contributor with two different ids, if i have multiple lang servers for same file ext, the same content gonna be contributed by the two contributors right ? Or am i missing something ?

**Comment by gayanper** [comment] 2019-04-08 17:03
@NipunaRanasinghe @nixel2007 How should i try to send configuration to language server as done at 

https://github.com/spring-projects/sts4/blob/master/eclipse-language-servers/org.springframework.tooling.boot.ls/src/org/springframework/tooling/boot/ls/DelegatingStreamConnectionProvider.java#L123

Seems like the code related to this in intellij plugin is in LanguageServerWrapper. How should we try to approach this, i'm kind of out of idea right now :( ?

**Comment by nixel2007** [comment] 2019-04-08 17:07
@gayanper i haven't digged into it yet. but i need configuration send method also :)

**Comment by NipunaRanasinghe** [comment] 2019-04-09 05:07
@gayanper @nixel2007 We need to add this capability as discussed with @nixel2007 earlier. We need to expose this API through `IntelliJLanguageClient` same as the other APIs which we have now.

**Comment by gayanper** [comment] 2019-04-09 05:48
@NipunaRanasinghe we still need a life cycle notification to trigger this method right ?. Or we should provide a hook which we can hook our post initialization so that the consumer can call the config method in that.

**Comment by gayanper** [comment] 2019-04-23 04:07
@NipunaRanasinghe @rasika I have created a gitter channel for this plugin to collaborate at https://gitter.im/ballerina-platform-lsp4intellij/community

I have already invited you into it. I hope with that we can avoid this kind of [question] issues. If a [question] is reoccurring that we can move to a FAQ in the wiki. What do you think ?

**Comment by NipunaRanasinghe** [comment] 2019-04-24 10:00
@gayanper You just made our life easier! :D I'm so +1 for this.

**Comment by swissiety** [comment] 2020-12-29 11:15
I guess we can close this issue after someone added the gitter channel to the readme?

**Comment by NipunaRanasinghe** [comment] 2024-05-12 13:13
Closing as the migration is completed and, gitter chanel is updated in the README to collaborate for the similar discussions in the future

**Closed by NipunaRanasinghe** 2024-05-12 13:13 UTC
Labels: good first issue, question
