### ISSUE TITLE
[critical bug] Duplicate entries when applying a code completion

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#59] opened 2019-04-24 16:46 UTC
When applying code completion a duplicate value is inserted. Following is a animation which shows the problem.

**Comment by gayanper** [comment] 2019-04-24 16:51
For some reason i cannot attach the raw mp4 file, so i have zipped it.
[Screencast.zip](https://github.com/ballerina-platform/lsp4intellij/files/3113362/Screencast.zip)

**Comment by NipunaRanasinghe** [comment] 2019-04-25 02:21
@gayanper Unfortunately I couldn't reproduce the issue with ballerina language server :? Is there any chance that your server response contains duplicated entities? could you please debug and verify?

**Comment by gayanper** [comment] 2019-04-25 02:27
I checked the same lang server with eclipse, but the problem is not there. Strange. But i will check the idea implementation and update this issue

**Comment by gayanper** [comment] 2019-04-25 16:52
@NipunaRanasinghe i debugged the plugin, there are no duplicate completions, what i found out was that, when selecting the completion the provided lookupString (in our case label or insertText) gets inserted into the editor and they the TextEdit gets inserted in front of it. I'm not really sure why that it happens nor the contract of the LookupElementBuilder :(. Hope this helps you the trouble shoot.

**Comment by gayanper** [comment] 2019-04-26 05:23
@NipunaRanasinghe may we might have missed some methods when converting to java https://sourcegraph.com/github.com/gtache/intellij-lsp@master/-/blob/intellij-lsp/src/com/github/gtache/lsp/editor/EditorEventManager.scala#L280:7-280:17

**Comment by NipunaRanasinghe** [comment] 2019-04-26 05:34
@gayanper Thanks for the observations. I'll have a look. :)

**Comment by gayanper** [comment] 2019-04-26 16:55
@NipunaRanasinghe please check this fix if its works fine with your language editor as well. https://github.com/ballerina-platform/lsp4intellij/pull/63

**Comment by NipunaRanasinghe** [comment] 2019-04-29 04:34
@gayanper Unfornately this fix breaks ballerina code completion :) Will update you after observing the reason

**Comment by NipunaRanasinghe** [comment] 2019-04-29 04:50
@gayanper I think I found the reason. lsp4j specification, text that is inserted when selecting a completion should be fetched according to the following priority.
1. label
2. textEdit 
3. insertText

You can refer the documentation at https://github.com/eclipse/lsp4j/blob/58bd73af0b7b62610e626aaaf1a625c1d57ccb1d/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/CompletionItem.java.

Shall we fix the issue accordingly? :)

**Comment by gayanper** [comment] 2019-04-29 05:45
Hmmmm sure, will you have time to look at it ? Otherwise i can take look at it tonight 🙂

**Comment by NipunaRanasinghe** [comment] 2019-04-29 05:59
@gayanper I was gonna tell you that I can work on this if you have less time :) I'll start working on the fix.

**Comment by gayanper** [comment] 2019-04-29 06:06
Thanks @NipunaRanasinghe

**Comment by gayanper** [comment] 2019-04-29 15:14
@NipunaRanasinghe shall i close my PR since you are working on this now ?

**Comment by gayanper** [comment] 2019-04-29 16:07
@NipunaRanasinghe never mind i had some spare time after fixing the symbol issue, so i fixed this as well according to you suggestions. Lets me know how it works now with the BAL LS.

**Comment by NipunaRanasinghe** [comment] 2019-05-13 03:21
Closing since fixed by #63.

**Closed by NipunaRanasinghe** 2019-05-13 03:21 UTC
Labels: Severity/Critical, Type/Bug
