### ISSUE TITLE
Assertion error when closing editor

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#186] opened 2020-04-21 18:50 UTC
`java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:174)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:183)
	at com.intellij.openapi.editor.impl.EditorImpl.removeEditorMouseMotionListener(EditorImpl.java:1760)
	at org.wso2.lsp4intellij.editor.EditorEventManager.removeListeners(EditorEventManager.java:1192)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.LanguageServerWrapper.disconnect(LanguageServerWrapper.java:618)
	at org.wso2.lsp4intellij.IntellijLanguageClient.lambda$editorClosed$9(IntellijLanguageClient.java:281)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

This is due to removing the motionlistener twice, do this really needed ?
```java
    public void removeListeners() {
        editor.getDocument().removeDocumentListener(documentListener);
        editor.removeEditorMouseListener(mouseListener);
        editor.removeEditorMouseMotionListener(mouseMotionListener);
        editor.removeEditorMouseMotionListener(mouseMotionListener);
        // Todo - Implement
        // editor.getSelectionModel.removeSelectionListener(selectionListener)
    }
```

**Comment by gayanper** [comment] 2020-04-21 19:47
@NipunaRanasinghe if i'm correct this is fixed in latest release right ?

**Comment by NipunaRanasinghe** [comment] 2020-04-22 05:38
@gayanper This was actually a regression caused by an external PR, which I fixed in the last release. Could you please try the latest library version and confirm so that we can close this?

**Closed** 2020-04-22 14:39 UTC
Labels: Resolution/Fixed, Type/Bug
